# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b2ff4b80e0143efdb31caef32874a2e027211a85d84bd2760968e73da770fb867174dd406a5dda59e0c0b773f653608ee524ba4c9e2640103a0b7c37d2560bf

test:
  secret_key_base: e4fd7c50fa508204a3370fe39c687cbd3252d4542b1f33d9201478bf255ebdbbd2472660b7a2c2bf81faf08cc0060a7b35d12cd4380c7279913546faece00140

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
